### ISSUE TITLE
Support multiline attributes

### ISSUE THREAD

**Issue by nervecenter** [rejectedsoftware/vibe.d#1307]
Jade currently supports multiline attributes, like so:

```
input(
    type='checkbox'
    name='agreement'
    checked
)
```

This would be an excellent feature for Diet.

**Comment by burner** [comment]
that would be great, but I would like to see an additional comma to make the syntax less ambiguous

```
 input(
    type='checkbox',
    name='agreement',
    checked
)
```

**Comment by burner** [comment]
I have been looking at the parser and don't see this happening this easy. But a maybe something like:

```
input(                           \
    type='checkbox',      \
    name='agreement',  \
    checked                   \
)
```

allows for a preprocessing step to transfrom the above code into a single line similar to Makefiles

**Comment by burner** [comment]
@s-ludwig would that be an option

**Comment by s-ludwig** [comment]
I'd rather not introduce additional syntax due to shortcomings of the current implementation. I'm (slowly) working on a [successor implementation](https://github.com/rejectedsoftware/diet-ng), which makes this much easier, so I'd concentrate the effort on that one. It still has to show if it will be able to compile real-world sized templates due to its presumably increased memory use, or if DMD's CTFE engine needs a rewrite first.

**Comment by burner** [comment]
hm, nice to know. I will have a look.

on a site note, adding the backslash thing is properly isn't hard. removeEmptyLines is the place to do it, I think
