### ISSUE TITLE
Multiple values in web forms

### ISSUE THREAD

**Issue by jkm** [rejectedsoftware/vibe.d#1309]
What's vibe.d's stand on multiple values in web forms? There seems no standard across web frameworks ([wikipedia query string](https://en.wikipedia.org/wiki/Query_string#Web_forms)).
The place to add is ```parseURLEncodedForm``` I'll guess.

**Comment by s-ludwig** [comment]
On the HTTP layer this is already supported using [`FormFields.getAll`](http://vibed.org/api/vibe.utils.dictionarylist/DictionaryList.getAll) or using `opApply`. The web framework (`vibe.web.web`) currently doesn't support it, because it still requires a decision on how to annotate parameters accordingly (e.g. using a UDA or a special type, or maybe even using auto-detection at runtime).

**Comment by jkm** [comment]
```getAll``` is fine in my case. Thanks. Sorry for the noise.
