### ISSUE TITLE
HTTPS client regression?

### ISSUE THREAD

**Issue by japplegame** [rejectedsoftware/vibe.d#1325]
After upgrading from 0.7.26-rc.1 to 0.7.26, this code:
```d
requestHTTP("https://steamcommunity.com",
	(scope HTTPClientRequest req) {},
	(scope HTTPClientResponse res) {}
);
```
causes error:
```
Task terminated with uncaught exception: Peer failed the certificate validation: 20
```
I found that reason is commit 7e8fcc48b527251f26fdb1d5a8fb88bd43a62fcf
After reversing appropriate diff, error has gone.

**Comment by punkUser** [comment]
Yeah I noticed the same thing - posted some more details here:
http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/27364/#post-27369

Don't totally understand the surrounding code but it looks like before it was ignoring the fact that it couldn't verify the server certificate for client requests (due to lack of a certificate store) but that new code triggers and fails SSL requests pretty uniformly now.

Interesting it doesn't trigger if you connect to the example HTTPS server. I'm guessing that's because that uses a self-signed certificate or similar which probably hits a slightly different error return in the switch statement below where it ignores it.
