### ISSUE TITLE
Signal handling setup in shared static this

### ISSUE THREAD

**Issue by jkm** [rejectedsoftware/vibe.d#1333]
The signal handling setup in a ```shared static this``` looks weired to me. What if I want my own signal handling? Also signal handling is inherited when forking. I'm unsure whether vibe should setup these handlers. At least it should be optional and a stop function to exit the event loop should be exposed.
Feel free to disagree.

**Comment by s-ludwig** [comment]
Since `vibe.core.core`'s `shared static this` is executed before any of the application, you are free to override the signal handling in any way you'd like. There is `vibe.core.core.exitEventLoop` to stop the event loop. The existing setup just tries to make a best effort to cleanly shut down the application on request - but it could definitely try harder, for example by supporting a user callback for customization.

**Comment by jkm** [comment]
I see. The current setup sets a default how to stop the application. Now assume I don't want that. I want the system default signal handlers or say some other code set them. I have no way to get the old signal handlers because as you say ```shared static this``` is executed before any of the application.
I just found this out because I was forking other processes and I was unable to kill them. I know I can hack around (provide my own handler even though the default would be fine). But to me this looks bad if I have to hack around.
Does this make sense?

**Comment by s-ludwig** [comment]
Have you tried `signal(SIGINT, SIG_DFL);`? That's supposed to reset back to the default handler.

**Comment by jkm** [comment]
No. I didn't know ```SIG_DFL```. I will do. But it still feels weired that I have to do this. Because I now have to figure out which handlers where set etc. Basically undoing vibe's signal handling.

**Comment by s-ludwig** [comment]
The best I can offer is adding a `VibeNoSignalHandlers` version identifier (and of course to document the exact signal behavior). The alternative would be to require everyone to set a signal handler on their own to get a clean shutdown, which is not really acceptable IMO.

**Comment by jkm** [comment]
For the moment just leave it as is. It's minor. Important for me that we do agree that there is a problem, even though it won't need immediate fixing.
Instead of the version identifier provide a function to setup the signal handling and one to turn it off. By default call the former of those functions. One can call the latter to turn it off. So I wouldn't introduce a version identifier.

**Comment by s-ludwig** [comment]
A function would indeed be another option, but with those semantics to me it feels like a crutch. It would be much cleaner to skip the setup in the first place, instead of reverting it later on. An idea would be to defer the signal setup to the first call to `runEventLoop`, then the application would have the chance to toggle a flag from within the static constructor.

**Comment by jkm** [comment]
Setting up the signal handlers later is definitely better. But still I would provide these functions because this allows manual intervention. I mean a good default setup that can be manually changed.
BTW vibe uses the static constructors much. Is there a reason why?

**Comment by s-ludwig** [comment]
> Setting up the signal handlers later is definitely better. But still I would provide these functions because this allows manual intervention. I mean a good default setup that can be manually changed.

You'd be able to do that with the mentioned flag (which would also be set by a similar function). Do you have a use case in mind for changing the settings while the program is already running as opposed to during initialization time? I can't really see any and just generally don't want to add features without one. To me this really seems like a simple static decision per program and I can't even see a need for making this runtime configurable, which is why I proposed a version identifier.

API-wise I'd rather go into a direction where more user customization is possible, so that the handlers are still registered by vibe.d by default, but the higher level code can set a callback to perform custom behavior (e.g. `exit(n)` or waiting for existing requests to finish).

> BTW vibe uses the static constructors much. Is there a reason why?

Convenience (less to no boilerplate - to write and to learn) and reducing the risk of bugs due to forgotten teardown (or setup) calls. With D's well defined module constructor behavior, initialization (and initialization order and all that) can be a pure implementation detail, as it ideally should be.

**Comment by jkm** [comment]
I think startup/initialization time should be fine.
