### ISSUE TITLE
"in" no longer works when trying to check if a cookie is in a CookieValueMap

### ISSUE THREAD

**Issue by SerialVelocity** [rejectedsoftware/vibe.d#1371]
Hey,

I've noticed that "opBinaryRight" in CookieValueMap has been commented out. This is breaking using "in" for checking if a cookie exists. Is there a particular reason for this? I couldn't really find any information about it within the commit.

Best,
SerialVelocity

**Comment by s-ludwig** [comment]
The reason was that now the raw cookie value is stored within the map instead of the decoded one, so that no pointer to the decoded value can be returned anymore. The way this will probably have to go is to first add a special struct, defining the `*` operator that gets returned instead. At the same time, the `in` operator would get deprecated, so that at some point it can be reintroduced to return the raw value.

Unfortunately, always treating cookies as URL encoded has been an early design mistake that makes this really inconvenient.
