### ISSUE TITLE
Bson corrupts some float data

### ISSUE THREAD

**Issue by denizzzka** [rejectedsoftware/vibe.d#1403]
```d
void main()
{
    import vibe.data.bson;
    import std.stdio;

    float f = -12.3456;
    double d = -12.3456;

    double from_float = cast(double) f;

    Bson b1, b2;
    b1 = Bson(from_float);
    b2 = Bson(d);

    writeln(b1);
    writeln(b2);

    assert(b1 == b2);
}
```

```
$ dub run --force
Performing "debug" build using dmd for x86_64.
vibe-d:utils 0.7.27-rc.2: building configuration "library"...
vibe-d:data 0.7.27-rc.2: building configuration "library"...
float ~master: building configuration "application"...
Linking...
Running ./float 
-12.34560012817383
-12.3456
core.exception.AssertError@source/app.d(18): Assertion failure
----------------
??:? _d_assert [0x4e7cf7]
??:? void app.__assert(int) [0x4c042f]
source/app.d:12 _Dmain [0x4b529f]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x4eb186]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4eb0c4]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4eb142]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4eb0c4]
??:? _d_run_main [0x4eb021]
??:? main [0x4c047f]
??:? __libc_start_main [0xf3dbcb44]
Program exited with code 1
```

**Comment by denizzzka** [comment]
Linux localhost 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux
DMD64 D Compiler v2.070.0

**Comment by csmith1991** [comment]
The issue isn't `Bson` its your comparison. `assert(d == from_float);` fails too.

Try `assert(approxEqual(b1, b2)); //approxEqual is in std.math`

**Comment by denizzzka** [comment]
Lol, ok.

but why 
> Try assert(approxEqual(b1, b2)); //approxEqual is in std.math
?

float is smaller whan double, double can fit float without approximation

**Comment by csmith1991** [comment]
Because you didn't specify exactly `-12.3456`. 

float isn't a decimal type in D (or most languages for that matter). Basically what happened is `-12.3456` got approximated with more precision than a float can store, so truncation took place. The amount of truncation necessary for the same number with double floating point precision was obviously less, so naturally you end up having `b1 < b2` in your example.

[Here's an article about floating point numbers within D](https://dlang.org/d-floating-point.html).
