### ISSUE TITLE
vibe.core.concurrency.receiveTimeout run error on master version

### ISSUE THREAD

**Issue by mzfhhhh** [rejectedsoftware/vibe.d#1408]
master version:
vibe.core.concurrency.receiveTimeout
run error
output:Cannot receive a message until a thread was spawned or thisTid was passed to a running thread

0.7.26 version:run ok

**Comment by s-ludwig** [comment]
This is caused by re-enabling the `std.concurrency` integration code that was accidentally left disabled for a while now. Have you tried querying `thisTid` before calling `receiveTimeout`? I don't remember the code in `std.concurrency`, but it might lazily create the message queue. The alternative, which is fully equivalent to what 0.7.26 did, is to use `receiveTimeoutCompat`/`sendCompat` - these are vibe.d's own implementation and will stay for a while to enable a proper transition (`std.concurrency` still has some issues, such as not supporting all safe object types to be passed to spawned tasks).

**Comment by mzfhhhh** [comment]
my test code is simple:
```D
shared static this(){		 
    runTask({
        if(!vibe.core.concurrency.receiveTimeout(3.seconds,(immutable(ubyte)[] buf){
            logInfo("%s",buf); 
        })){
            logInfo("timeout"); 
        }
    });
}
```

now i use "receiveTimeoutCompat",it's works ok. thanks

**Comment by s-ludwig** [comment]
Just beware that you'll also have to use `sendCompat`! But I've just discovered a potential way to work around this within vibe.d - I'll look into that.

**Comment by s-ludwig** [comment]
Okay, should be working now. Also fixed an issue where messages of a previous task could end up in the message queue of a new task.
