### ISSUE TITLE
Empty Json serializes to "undefined"

### ISSUE THREAD

**Issue by SmorkalovG** [rejectedsoftware/vibe.d#1442]
Why is Json().toString "undefined"? It is not a valid json, I can not pass it to the client.

**Comment by SmorkalovG** [comment]
Accidentally created the issue before wrote body. Sorry.
I am trying to use REST interface generator. The result of some method is:
struct Test {
	ushort port;
	string path;
	Json arguments;
}
If method returns Test(8081, "/", Json()) then serialized json is {"port":8081,"path":"/","arguments":undefined}. It isn't valid. May be it is better to serialize Json() to {} or null?
If not, is there another way to add optional field to struct with arbitrary data?

**Comment by s-ludwig** [comment]
Try to use `Json arguments = Json.emptyObject;` in this case. `Json.undefined` is used, because everything else would be arbitrary, it could otherwise mean any of `null`, `{}` or `[]`, but which of these makes sense depends on the situation.

If you need an optional field, you have two other possibilities:
- Use the `@optional` attribute on the field in question, if optionality on the receiving side is enough (it will always be serialized when serializing)
- Use `Nullable!T`. In this case, `null` will be used to denote the missing field.

It would be nice if Phobos also had an `Optional!T` type. I'd add support for it, so that the field is completely omitted if the `Optional` isn't set.

**Comment by SmorkalovG** [comment]
Thank you for answer. Now I understand how to solve my problem.
But I still don't understand why it is possible to get invalid json as result of serialization. In my point of view it is a design problem. I think nothing should lead to invalid json. And there are not many ways to get rid of this behavior. Json().toString must throw an exception or return valid json (i.e. {} or null). Are there any reasons why it is "undefined"? Because it is human readable?

**Comment by s-ludwig** [comment]
Oh, you are absolutely right, I missed that part. There are related tickets (#222, #958) and a partial PR (#1323). I think the best solution would be to follow JavaScript's rules for this - if an object has a field with an undefined value, skip it during serialization and else output `null` instead.

**Comment by SmorkalovG** [comment]
Sorry, I thought PR fixes this situation. It is better if issue will be opened until it is fixed.

**Comment by s-ludwig** [comment]
Fixed by https://github.com/rejectedsoftware/vibe.d/pull/1548
