### ISSUE TITLE
@safe-ty for vibe.core.stream

### ISSUE THREAD

**Issue by Abscissa** [rejectedsoftware/vibe.d#1595]
If vibe.core.stream can be given the @safe/@trusted treratment, then mysql-native (or anything else that uses vibe streams) can start doing @safe too. Phobos's sockets seem to be @safe-compatible as of 2.067.

**Comment by s-ludwig** [comment]
I'm currently in the process of `@safe`tifying almost everything to be able to swap out `vibe:core` for `vibe-core` (which already defines the streams as `@safe`). The viral nature of `@safe` makes this a large change, but it will be in the next version (0.8.0). Unfortunately there are still lots of Phobos functions that are `@system`, so that littering the code with `() @trusted { ... } ()` is necessary.

**Comment by s-ludwig** [comment]
Implemented by #1618.
