### ISSUE TITLE
Content Type for RestInterface

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1601]
My current project provides a REST API to be used by a front end written in [Ember](http://emberjs.com/). They favour making the backend conform to the [JSON API](http://jsonapi.org/) conventions. Part of which is to use the content type `application/vnd.api+json`.

So I've got the following where 'JsonApiImpl' is a class defining my endpoints:

``` D
auto router = new URLRouter;
auto apiSettings = new RestInterfaceSettings;
apiSettings.baseURL = URL("/api");
apiSettings.allowedOrigins = ["*"];
router.registerRestInterface(new JsonApiImpl, apiSettings);
```

The default seems to be to return the content type `application/json` but I can't seem to see a convenient way to set it to what I need.

**Comment by SingingBush** [comment]
Looks like it should be done in [lines 214-240](https://github.com/rejectedsoftware/vibe.d/blob/f74749618701126b26642b4bea0222ccdae9437b/web/vibe/web/rest.d#L214-L240) of `vibe.web.rest`.

**Comment by s-ludwig** [comment]
If I understand correctly, the custom content type would have to be injected here: https://github.com/rejectedsoftware/vibe.d/blob/2daaec4673bcb6806201c106bfac80e8972c305c/web/vibe/web/rest.d#L1125 (as well as for the two following calls).

This could be done using an `@after` annotation, but currently doesn't, because `writeJsonBody` always overwrites the content type header. My first fix would be to change that and only let it set it, if it hasn't been written already. Then the following could be used:

```
class MyService : IMyService {
@after!setContentType:

    void getSomething() {...}
    void getSomethingElse() {...}
}

void setContentType(HTTPServerRequest req, HTTPServerResponse res)
{
    res.headers["Content-Type"] = "application/vnd.api+json; charset=UTF-8";
}
```

A more integrated solution should be added later, once it is also clear how to support custom data  formats such as XML.

**Comment by s-ludwig** [comment]
Okay, this has been implemented on master now.

**Comment by SingingBush** [comment]
thanks, I can confirm that this is sorted in 0.7.31-alpha.1

In the end, as I need that header on all responses I have used:

```D
router.any("*", delegate(req, res) {
                res.headers["Content-Type"] = `application/vnd.api+json`;
            })
```

which was not possible before.
