### ISSUE TITLE
vibe-d 0.8.0-beta breaks mysql-native

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1664]
updating to the latest vibe-d 0.8.0-beta causes a [problem for mysql-native-0.1.7](https://github.com/mysql-d/mysql-native/issues/92):

```
~/.dub/packages/mysql-native-0.1.7/mysql-native/source/mysql/db.d(35,13): Error: constructor vibe.core.connectionpool.ConnectionPool!(Connection).ConnectionPool.this (Connection delegate() @safe connection_factory, uint max_concurrent = 4294967295u) is not callable using argument types (Connection delegate())
```

Is possible to keep compatibility?

**Comment by Abscissa** [comment]
Looks like the problem is that `vibe.core.connectionpool.ConnectionPool.this` is now requires the delegate you pass it to be @safe.

Is that restriction really, truly necessary right now? Can ConnectionPool just become templated so whatever relevant code on vibe's side can just inheret its @safe-ty from that callback?

It's a bit of a problem for mysql-native at the moment, because if openening a connection must be @safe, then that has enough of a cascading effect that most of the mysql-native must become @safe. Worse, last time I tried to do that, it required large parts of vibe-d:core to become @safe as well, which means, *at best*, mysql-native must drop compatibility for all vibe-d prior to 0.8.0 *and* at least a couple versions of DMDFE. I'm not sure I'm really comfortable doing that yet.

Technically, I guess I *could* just slap a @trusted on the callback mysql-native passes to vibe's ConenctionPool, but that seems like a great abuse of the @safe-ty system.

**Comment by s-ludwig** [comment]
`@trusted` looks like the only immediate solution right now, either in mysql-native or in vibe.d. A template solution doesn't work, because then the enclosing class type would have to be inferred from the constructor call. If construction would work using a factory function, that would have been less of an issue, but there still remains the problem that there will often be declarations of the form `ConnectionPool!C pool`, which would now have to include the safety flag.

But I can at least add a `@trusted` constructor overload with a deprecation warning, which is what is already in place for most other similar functions. BTW, most of vibe.d *is* now `@safe` (this has been a *huge* change set), so templating things in mysql-native to infer safety would be a possibility, too.

**Comment by SingingBush** [comment]
yep, that's sorted now in vibe-d 0.8.0-beta.3
