### ISSUE TITLE
dub is hang on if view folder have nodejs init-ed project inside it

### ISSUE THREAD

**Issue by bubnenkoff** [rejectedsoftware/vibe.d#1690]
I develop web app. It's view-part is nodejs based. So I have in `views` folder nodejs project.

But when I trying to build project dub is hang on. I tried to remove content of `views` folder and only after it I was able to build project. It's seems that dub is trying to analyze this folder.

Just try to build it. https://ufile.io/0a9e9

**Comment by s-ludwig** [comment]
The reason turned out to be that the `views` directory simply contains a lot of files and DUB had cubic runtime when collecting those files. The reason why it was collecting files in the "view" folder is that this folder is considered a string import folder by default. To avoid that, put `stringImportPaths` without arguments in dub.sdl.

I've propose a fix for DUB: https://github.com/dlang/dub/pull/1079

**Comment by s-ludwig** [comment]
Fixed for DUB master.
