### ISSUE TITLE
Call of getResult on Future returned by async hangs worker task

### ISSUE THREAD

**Issue by sturtivant** [rejectedsoftware/vibe.d#1717]
See <http://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/41623/>.

**Comment by s-ludwig** [comment]
Okay, this one is a bit tricky. I don't have a solution implemented yet, but the reason is relatively simple:

The parameters to `logInfo` are evaluated lazily while the mutex of the corresponding logger is in a locked state. This means that for `logInfo("%s", val.getResult());`, the mutex stays locked until `val.getResult()` has returned. When the worker thread now tries to log the next time stamp, it will attempt to acquire the log mutex, too, and hangs there forever in a deadlock.

The simple workaround is to get the result *before* calling `logInfo`. But a full solution could get somewhat tricky and I have to remember/research first why `logInfo`'s arguments are `lazy` instead of `auto ref`.

PS: Thank you for the donation!

**Comment by s-ludwig** [comment]
One effect of changing from `lazy` to `auto ref` turned out to be that statements like `logInfo("%s", exception.toString);` are not `nothrow` anymore. So changing it will probably result in a considerable amount of code breakage.
