### ISSUE TITLE
Doesn't build on Windows with `--build=x86_mscoff`

### ISSUE THREAD

**Issue by atilaneves** [rejectedsoftware/vibe.d#1771]
This is due to the libraries included for both optlink and 64-bit formats but not 32-bit MSCOFF

**Comment by s-ludwig** [comment]
The 64-bit build actually chooses the win32 configuration, which the 32-bit MSCOFF one should, too. The problem is that the mscoff pseudo-architecture "x86_mscoff" currently is also matched by the "x86" platform specifier, so this needs a crude workaround. We (@epi and me) a started to sketch/implement a clean solution for this, but the real work still lies ahead, AFAIK.

**Comment by s-ludwig** [comment]
See dlang/dub#228
