### ISSUE TITLE
vibe.d test hangs for several seconds before running event loop

### ISSUE THREAD

**Issue by MartinNowak** [rejectedsoftware/vibe.d#1844]
Reproducible on the CI server with v0.8.0-118-gbe6862a and  v0.8.0 in with tests/vibe.core.net.1726.

Apparently responsible for the failing tests https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-6993/3/pipeline#step-700-log-2012.

I've attached `--vvvv` and strace logs and marked the lines where it hangs.
[hang_strace.log.txt](https://github.com/rejectedsoftware/vibe.d/files/1150211/hang_strace.log.txt)
[hang_vibe_d.log.txt](https://github.com/rejectedsoftware/vibe.d/files/1150212/hang_vibe_d.log.txt)

Hope that helps to locate the cause.
libevent version is 2.0.21-stable-2ubuntu0.16.04.1

**Comment by MartinNowak** [comment]
I'm seeing some huge GC heap usage and lots of time in newArray and in evbuffer_add.
What's the point of sending 512MB over the wire?
https://github.com/rejectedsoftware/vibe.d/blob/ddae95929bea78aab84aca12aede653129beef2f/tests/vibe.core.net.1726/source/app.d#L8
Apparently this is supposed to fail for some reason but keeps running for quite a while until it does.
BTW, those 2 listenTCP calls collide cause the socket is still bound by the first listener.

**Comment by s-ludwig** [comment]
I accidentally broke the test when I tried to improve it (fooled by it seemingly passing). The listen issue, as well as the event loop interaction have been fixed now.

The intention is to not send any data at all, but to just fill the output buffer and have the `write` call block. The question is why the `mmap` call is invoked with 1 GiB instead of with 512 MiB. I'm not sure where the hang comes from, though. It seems to hang in `epoll_wait` before `write` was even called.

**Comment by MartinNowak** [comment]
Looks like simply lots of memory was hogged in the page cache (and btrfs caches), and it took the kernel ages to migrate and compact pages. So nothing specific about vibe.d. Using an uninitialized array might work around such problems.
