### ISSUE TITLE
Win64 libevent2 .lib and .dll missing

### ISSUE THREAD

**Issue by ColdenCullen** [rejectedsoftware/vibe.d#832]
event2.lib and libevent.dll are both in `lib/win-1386`, but not `lib/win-amd64` folder. This leads to an error when building a Windows application with --arch=x86_64.

**Comment by Kelet** [comment]
With the `x86_64-w64-mingw32` build of GDC, I get
```
gdc: error: C:\Users\Kelet\AppData\Roaming\dub\packages\vibe-d-0.7.23\lib\win-amd64\event2.lib: No such file or directory
```

Seems to be the same issue. Compiled with `dub build --compiler=gdc`.

**Comment by s-ludwig** [comment]
Since the future path will be to directly talk to the OS APIs without a C library in-between (as libasync does), it doesn't make sense to invest time building a Win64 version of libevent anymore (requires setting up a custom makefile/VS project). I've instead disabled the libevent configuration on Win64 now.

**Comment by etcimon** [comment]
Will you be developing your own library or are we still looking at making libasync default in the future?
