### ISSUE TITLE
weird crash when using phobos sha1 with vibe

### ISSUE THREAD

**Issue by Extrawurst** [rejectedsoftware/vibe.d#906]
running the code below inside a naked main() without vibe it does not crash. running it using vibe it carshes with an AV:
```
shared static this()
{
	import std.digest.sha;
 
	ubyte[20] hash = sha1Of("abc");
}
```

tested usung dmd 2.066.1 and vibe.d 0.7.21 on wn32

**Comment by stiXits** [comment]
I have the same Problem and tested it under deffirent Linux distributions. The error ocurred in combination with mysql-native (which is a quite common combination if you want to use ddbc or hibernated) and it took me a while to track it down to vibed (and this issue in particular). So as long as it's not fixed, this workaround should be easier to find.

**Comment by etcimon** [comment]
There's always a possibility that the `SHA1` module cannot query the `core.cpuid` module, possibly because it had not been loaded at that point in the `shared static this()` chain. Maybe you can try `import core.cpuid` in your module directly to make sure it's loaded, and see if `shared static this() { sha1Of...` can work that way?

**Comment by stiXits** [comment]
unfortunately no changes

**Comment by s-ludwig** [comment]
I think you are right about `shared static this`, @etcimon. Probably the initialization is done in `static this` instead of `shared static this`, which comes after processing all `shared` module constructors. The following also crashes without any vibe.d interaction:

```
import std.digest.sha;

shared static this()
{
	ubyte[4] buf = [1, 2, 3, 4];
	auto dig = sha1Of(buf);
}

void main() {}
```

Has anyone already filed/found a bug report on https://issues.dlang.org/?
